// Конфигурация всех инструментов PDF X
export const TOOLS = [
  { 
    id: "pdf2img", 
    route: "/pdf-to-image",
    emoji: "🖼️", 
    label: "PDF → Картинки", 
    hint: "PNG / JPEG каждой страницы", 
    accept: ".pdf", 
    multi: false, 
    color: "#a78bfa", 
    pro: false, 
    cat: "convert",
    title: "PDF в изображения — конвертируй страницы в PNG или JPEG",
    description: "Бесплатно конвертируй PDF в картинки высокого качества. Выбери формат PNG или JPEG, настрой масштаб. Всё в браузере — файлы не покидают устройство.",
    keywords: ["pdf в jpg", "pdf в png", "конвертер pdf", "извлечь страницы pdf", "pdf в картинки"]
  },
  { 
    id: "img2pdf", 
    route: "/image-to-pdf",
    emoji: "📄", 
    label: "Фото → PDF", 
    hint: "Собери PDF из изображений", 
    accept: "image/*", 
    multi: true, 
    color: "#60a5fa", 
    pro: false, 
    cat: "convert",
    title: "Изображения в PDF — объедини JPG и PNG в один документ",
    description: "Преобразуй JPG, PNG, WebP в PDF быстро и бесплатно. Настрой размер страницы и ориентацию. Приватно, без серверов.",
    keywords: ["jpg в pdf", "png в pdf", "создать pdf из фото", "объединить картинки в pdf"]
  },
  { 
    id: "merge", 
    route: "/merge-pdf",
    emoji: "🔗", 
    label: "Объединить PDF", 
    hint: "Склей несколько PDF", 
    accept: ".pdf", 
    multi: true, 
    color: "#34d399", 
    pro: false, 
    cat: "edit",
    title: "Объединить PDF — смержи несколько файлов в один",
    description: "Соедини несколько PDF документов в один файл онлайн. Меняй порядок страниц перетаскиванием. Бесплатно, без регистрации.",
    keywords: ["склеить pdf", "объединить pdf", "merge pdf", "смержить pdf файлы"]
  },
  { 
    id: "compress", 
    route: "/compress-pdf",
    emoji: "🗜️", 
    label: "Сжать PDF", 
    hint: "Уменьши вес файла", 
    accept: ".pdf", 
    multi: false, 
    color: "#fbbf24", 
    pro: false, 
    cat: "edit",
    title: "Сжать PDF онлайн — уменьши размер файла без потери качества",
    description: "Сжимай PDF до 90% без потери качества. Три уровня сжатия: сильное, среднее, слабое. Идеально для email и загрузки.",
    keywords: ["сжать pdf", "уменьшить pdf", "pdf compressor", "сжатие pdf онлайн"]
  },
  { 
    id: "rotate", 
    route: "/rotate-pdf",
    emoji: "🔄", 
    label: "Повернуть PDF", 
    hint: "Исправь ориентацию", 
    accept: ".pdf", 
    multi: false, 
    color: "#f87171", 
    pro: false, 
    cat: "edit",
    title: "Повернуть PDF — измени ориентацию страниц",
    description: "Поворачивай страницы PDF на 90°, 180°, 270°. Применяй ко всем страницам, только чётным или нечётным. Бесплатно онлайн.",
    keywords: ["повернуть pdf", "изменить ориентацию pdf", "rotate pdf", "pdf перевёрнутый"]
  },
  { 
    id: "split", 
    route: "/split-pdf",
    emoji: "✂️", 
    label: "Разделить PDF", 
    hint: "Извлеки нужные страницы", 
    accept: ".pdf", 
    multi: false, 
    color: "#fb923c", 
    pro: false, 
    cat: "edit",
    title: "Разделить PDF — извлеки страницы или разбей на части",
    description: "Раздели PDF на отдельные страницы или извлеки диапазон. Скачай каждую страницу отдельно или объедини в новый файл.",
    keywords: ["разделить pdf", "извлечь страницы pdf", "split pdf", "разбить pdf на страницы"]
  },
  { 
    id: "watermark", 
    route: "/watermark-pdf",
    emoji: "💧", 
    label: "Водяной знак", 
    hint: "Защити документ", 
    accept: ".pdf", 
    multi: false, 
    color: "#38bdf8", 
    pro: false, 
    cat: "protect",
    title: "Добавить водяной знак в PDF — защити документ",
    description: "Наложи водяной знак на PDF: Конфиденциально, Черновик, Копия или свой текст. Настрой прозрачность и цвет. Бесплатно онлайн.",
    keywords: ["водяной знак pdf", "защита pdf", "watermark pdf", "пометить pdf"]
  },
  { 
    id: "info", 
    route: "/analyze-pdf",
    emoji: "🔍", 
    label: "Анализ PDF", 
    hint: "Метаданные и структура", 
    accept: ".pdf", 
    multi: false, 
    color: "#a3e635", 
    pro: false, 
    cat: "analyze",
    title: "Анализ PDF — посмотри метаданные и свойства файла",
    description: "Узнай всё о PDF файле: количество страниц, размер, автор, шифрование, содержит ли текст или скан. Бесплатный анализ онлайн.",
    keywords: ["анализ pdf", "метаданные pdf", "информация о pdf", "pdf info"]
  },
  // PRO TOOLS
  { 
    id: "ocr", 
    route: "/ocr-pdf",
    emoji: "👁️", 
    label: "OCR текст", 
    hint: "Распознай текст из скана", 
    accept: ".pdf,image/*", 
    multi: false, 
    color: "#e879f9", 
    pro: true, 
    cat: "convert", 
    badge: "PRO",
    title: "OCR PDF — распознай текст из сканов и изображений",
    description: "Распознавай текст из отсканированных PDF и картинок. Поддержка русского и 100+ языков. PRO функция с высокой точностью.",
    keywords: ["ocr pdf", "распознать текст", "pdf в текст", "ocr онлайн", "распознавание текста"]
  },
  { 
    id: "extract", 
    route: "/extract-text",
    emoji: "📝", 
    label: "Извлечь текст", 
    hint: "Скопируй весь текст из PDF", 
    accept: ".pdf", 
    multi: false, 
    color: "#67e8f9", 
    pro: false, 
    cat: "convert",
    title: "Извлечь текст из PDF — скопируй содержимое",
    description: "Извлеки весь текст из PDF файла. Сохрани в TXT или скопируй в буфер обмена. Работает только с текстовыми PDF, не со сканами.",
    keywords: ["извлечь текст pdf", "pdf в txt", "текст из pdf", "скопировать текст pdf"]
  },
  { 
    id: "sign", 
    route: "/sign-pdf",
    emoji: "✍️", 
    label: "Подписать PDF", 
    hint: "Нарисуй подпись на PDF", 
    accept: ".pdf", 
    multi: false, 
    color: "#f0abfc", 
    pro: true, 
    cat: "protect", 
    badge: "PRO",
    title: "Подписать PDF — добавь электронную подпись",
    description: "Подписывай PDF документы онлайн. Нарисуй подпись мышкой или пальцем. Размести на любой странице. PRO функция.",
    keywords: ["подписать pdf", "электронная подпись", "sign pdf", "подпись на документе"]
  },
  { 
    id: "pagenum", 
    route: "/page-numbers",
    emoji: "🔢", 
    label: "Нумерация", 
    hint: "Добавь номера страниц", 
    accept: ".pdf", 
    multi: false, 
    color: "#86efac", 
    pro: true, 
    cat: "edit", 
    badge: "PRO",
    title: "Нумерация страниц PDF — добавь номера",
    description: "Добавь номера страниц в PDF. Настрой позицию, формат, шрифт. Нумеруй с любой страницы. PRO функция для профессиональных документов.",
    keywords: ["нумерация pdf", "номера страниц", "page numbers pdf", "добавить номера"]
  },
];

export const CATEGORIES = [
  { id: "all", label: "Все", emoji: "⚡" },
  { id: "convert", label: "Конвертация", emoji: "🔄" },
  { id: "edit", label: "Редактор", emoji: "✏️" },
  { id: "protect", label: "Защита", emoji: "🛡️" },
  { id: "analyze", label: "Анализ", emoji: "📊" },
];

export const FREE_OPS_PER_DAY = 5;
export const PRO_PRICE = "$2.99/мес";
