// Конфигурация инструментов PDF X
export const TOOLS = [
  {
    id: "merge",
    route: "/merge-pdf",
    emoji: "🔗",
    label: "Объединить PDF",
    hint: "Склей несколько PDF",
    accept: ".pdf",
    multi: true,
    color: "#34d399",
    pro: false,
    cat: "edit",
    title: "Объединить PDF - склейка файлов в один документ",
    description: "Объединяй несколько PDF-файлов в один итоговый документ.",
    keywords: ["объединить pdf", "склеить pdf", "merge pdf"],
  },
  {
    id: "split",
    route: "/split-pdf",
    emoji: "✂️",
    label: "Разделить PDF",
    hint: "Извлеки нужные страницы",
    accept: ".pdf",
    multi: false,
    color: "#fb923c",
    pro: false,
    cat: "edit",
    title: "Разделить PDF - извлечение страниц",
    description: "Разделяй PDF на диапазоны или отдельные страницы.",
    keywords: ["разделить pdf", "split pdf"],
  },
  {
    id: "compress",
    route: "/compress-pdf",
    emoji: "🗜️",
    label: "Сжать PDF",
    hint: "Уменьши размер файла",
    accept: ".pdf",
    multi: false,
    color: "#fbbf24",
    pro: false,
    cat: "edit",
    title: "Сжать PDF онлайн",
    description: "Уменьшай размер PDF без заметной потери качества.",
    keywords: ["сжать pdf", "compress pdf"],
  },
  {
    id: "rotate",
    route: "/rotate-pdf",
    emoji: "🔄",
    label: "Повернуть PDF",
    hint: "Исправь ориентацию",
    accept: ".pdf",
    multi: false,
    color: "#f87171",
    pro: false,
    cat: "edit",
    title: "Повернуть PDF",
    description: "Поворачивай страницы PDF на 90, 180 и 270 градусов.",
    keywords: ["повернуть pdf", "rotate pdf"],
  },
  {
    id: "deletepages",
    route: "/delete-pages",
    emoji: "🗑️",
    label: "Удалить страницы",
    hint: "Убери лишние листы",
    accept: ".pdf",
    multi: false,
    color: "#ef4444",
    pro: false,
    cat: "edit",
    title: "Удалить страницы PDF",
    description: "Удаляй ненужные страницы из PDF-документа.",
    keywords: ["удалить страницы pdf", "pdf delete pages"],
  },
  {
    id: "reorder",
    route: "/reorder-pages",
    emoji: "🧩",
    label: "Сортировать страницы",
    hint: "Измени порядок",
    accept: ".pdf",
    multi: false,
    color: "#14b8a6",
    pro: false,
    cat: "edit",
    title: "Сортировать страницы PDF",
    description: "Меняй порядок страниц в PDF перед выгрузкой.",
    keywords: ["порядок страниц pdf", "reorder pdf pages"],
  },
  {
    id: "extractpages",
    route: "/extract-pages",
    emoji: "📑",
    label: "Извлечь страницы",
    hint: "Собери новый PDF",
    accept: ".pdf",
    multi: false,
    color: "#f97316",
    pro: false,
    cat: "edit",
    title: "Извлечь страницы PDF",
    description: "Выделяй диапазоны и собирай из них новый PDF-файл.",
    keywords: ["извлечь страницы pdf", "extract pages pdf"],
  },
  {
    id: "crop",
    route: "/crop-pdf",
    emoji: "✂️",
    label: "Обрезать PDF",
    hint: "Подрежь поля",
    accept: ".pdf",
    multi: false,
    color: "#fb7185",
    pro: true,
    cat: "edit",
    title: "Обрезать PDF",
    description: "Обрезай поля страниц и лишние области в PDF.",
    keywords: ["обрезать pdf", "crop pdf"],
  },

  {
    id: "pdf2img",
    route: "/pdf-to-image",
    emoji: "🖼️",
    label: "PDF в Картинки",
    hint: "PNG/JPG каждой страницы",
    accept: ".pdf",
    multi: false,
    color: "#a78bfa",
    pro: false,
    cat: "convert",
    title: "PDF в изображения",
    description: "Конвертируй страницы PDF в PNG и JPG.",
    keywords: ["pdf в jpg", "pdf в png", "pdf to image"],
  },
  {
    id: "pdf2jpg",
    route: "/pdf-to-jpg",
    emoji: "🟨",
    label: "PDF в JPG",
    hint: "Экспорт в JPG",
    accept: ".pdf",
    multi: false,
    color: "#f59e0b",
    pro: false,
    cat: "convert",
    title: "PDF в JPG",
    description: "Сохраняй страницы PDF как JPG-файлы.",
    keywords: ["pdf в jpg", "pdf to jpg"],
  },
  {
    id: "pdf2png",
    route: "/pdf-to-png",
    emoji: "🟧",
    label: "PDF в PNG",
    hint: "Экспорт без потерь",
    accept: ".pdf",
    multi: false,
    color: "#f97316",
    pro: false,
    cat: "convert",
    title: "PDF в PNG",
    description: "Конвертируй PDF в PNG для максимальной четкости.",
    keywords: ["pdf в png", "pdf to png"],
  },
  {
    id: "img2pdf",
    route: "/image-to-pdf",
    emoji: "📄",
    label: "Фото в PDF",
    hint: "Собери PDF из картинок",
    accept: "image/*",
    multi: true,
    color: "#60a5fa",
    pro: false,
    cat: "convert",
    title: "Изображения в PDF",
    description: "Объединяй изображения в один PDF-документ.",
    keywords: ["image to pdf", "фото в pdf"],
  },
  {
    id: "jpg2pdf",
    route: "/jpg-to-pdf",
    emoji: "🟨",
    label: "JPG в PDF",
    hint: "JPG в один документ",
    accept: "image/jpeg,image/jpg",
    multi: true,
    color: "#facc15",
    pro: false,
    cat: "convert",
    title: "JPG в PDF",
    description: "Преобразуй JPG-изображения в PDF.",
    keywords: ["jpg в pdf", "jpg to pdf"],
  },
  {
    id: "png2pdf",
    route: "/png-to-pdf",
    emoji: "🟧",
    label: "PNG в PDF",
    hint: "PNG в один PDF",
    accept: "image/png",
    multi: true,
    color: "#fb923c",
    pro: false,
    cat: "convert",
    title: "PNG в PDF",
    description: "Преобразуй PNG-файлы в PDF-документ.",
    keywords: ["png в pdf", "png to pdf"],
  },
  {
    id: "word2pdf",
    route: "/word-to-pdf",
    emoji: "📝",
    label: "Word в PDF",
    hint: "DOC/DOCX в PDF",
    accept: ".doc,.docx",
    multi: true,
    color: "#3b82f6",
    pro: false,
    cat: "convert",
    title: "Word в PDF",
    description: "Конвертируй DOC/DOCX документы в PDF.",
    keywords: ["word в pdf", "docx в pdf"],
  },
  {
    id: "pdf2word",
    route: "/pdf-to-word",
    emoji: "📘",
    label: "PDF в Word",
    hint: "PDF в DOCX",
    accept: ".pdf",
    multi: false,
    color: "#2563eb",
    pro: true,
    cat: "convert",
    title: "PDF в Word",
    description: "Преобразуй PDF в редактируемый DOCX.",
    keywords: ["pdf в word", "pdf to docx"],
  },
  {
    id: "excel2pdf",
    route: "/excel-to-pdf",
    emoji: "📗",
    label: "Excel в PDF",
    hint: "XLS/XLSX в PDF",
    accept: ".xls,.xlsx",
    multi: true,
    color: "#22c55e",
    pro: false,
    cat: "convert",
    title: "Excel в PDF",
    description: "Конвертируй таблицы Excel в PDF-файл.",
    keywords: ["excel в pdf", "xlsx в pdf"],
  },
  {
    id: "pdf2excel",
    route: "/pdf-to-excel",
    emoji: "📊",
    label: "PDF в Excel",
    hint: "Извлечение таблиц",
    accept: ".pdf",
    multi: false,
    color: "#16a34a",
    pro: true,
    cat: "convert",
    title: "PDF в Excel",
    description: "Извлекай таблицы из PDF в XLSX.",
    keywords: ["pdf в excel", "pdf to xlsx"],
  },
  {
    id: "ppt2pdf",
    route: "/ppt-to-pdf",
    emoji: "📙",
    label: "PPT в PDF",
    hint: "PPT/PPTX в PDF",
    accept: ".ppt,.pptx",
    multi: true,
    color: "#f97316",
    pro: false,
    cat: "convert",
    title: "PPT в PDF",
    description: "Преобразуй презентации PowerPoint в PDF.",
    keywords: ["ppt в pdf", "pptx в pdf"],
  },
  {
    id: "pdf2ppt",
    route: "/pdf-to-ppt",
    emoji: "📕",
    label: "PDF в PPT",
    hint: "PDF в презентацию",
    accept: ".pdf",
    multi: false,
    color: "#ea580c",
    pro: true,
    cat: "convert",
    title: "PDF в PPT",
    description: "Конвертируй PDF в редактируемый формат презентации.",
    keywords: ["pdf в ppt", "pdf to powerpoint"],
  },
  {
    id: "html2pdf",
    route: "/html-to-pdf",
    emoji: "🌐",
    label: "HTML в PDF",
    hint: "Сайт в PDF",
    accept: ".html,.htm",
    multi: false,
    color: "#8b5cf6",
    pro: false,
    cat: "convert",
    title: "HTML в PDF",
    description: "Преобразуй HTML-файлы в PDF-документ.",
    keywords: ["html в pdf", "html to pdf"],
  },
  {
    id: "pdf2html",
    route: "/pdf-to-html",
    emoji: "💻",
    label: "PDF в HTML",
    hint: "PDF в веб-формат",
    accept: ".pdf",
    multi: false,
    color: "#7c3aed",
    pro: true,
    cat: "convert",
    title: "PDF в HTML",
    description: "Экспортируй PDF в HTML для публикации на сайте.",
    keywords: ["pdf в html", "pdf to html"],
  },
  {
    id: "txt2pdf",
    route: "/text-to-pdf",
    emoji: "📄",
    label: "TXT в PDF",
    hint: "Текст в PDF",
    accept: ".txt",
    multi: true,
    color: "#6366f1",
    pro: false,
    cat: "convert",
    title: "TXT в PDF",
    description: "Конвертируй текстовые файлы в PDF.",
    keywords: ["txt в pdf", "text to pdf"],
  },
  {
    id: "scan2pdf",
    route: "/scan-to-pdf",
    emoji: "📷",
    label: "Скан в PDF",
    hint: "Фото документов в PDF",
    accept: "image/*",
    multi: true,
    color: "#0ea5e9",
    pro: false,
    cat: "convert",
    title: "Скан в PDF",
    description: "Собирай фото документов в единый PDF.",
    keywords: ["scan to pdf", "скан в pdf"],
  },
  {
    id: "pdfa",
    route: "/pdf-to-pdfa",
    emoji: "🗂️",
    label: "PDF в PDF/A",
    hint: "Архивный стандарт",
    accept: ".pdf",
    multi: false,
    color: "#16a34a",
    pro: true,
    cat: "convert",
    title: "PDF в PDF/A",
    description: "Преобразуй PDF в архивный формат PDF/A.",
    keywords: ["pdfa", "pdf в pdfa"],
  },

  {
    id: "protect",
    route: "/protect-pdf",
    emoji: "🛡️",
    label: "Защитить PDF",
    hint: "Поставь пароль",
    accept: ".pdf",
    multi: false,
    color: "#22c55e",
    pro: false,
    cat: "protect",
    title: "Защитить PDF",
    description: "Установи пароль и ограничения доступа для PDF.",
    keywords: ["защитить pdf", "pdf password"],
  },
  {
    id: "unlock",
    route: "/unlock-pdf",
    emoji: "🔓",
    label: "Снять защиту",
    hint: "Разблокируй PDF",
    accept: ".pdf",
    multi: false,
    color: "#10b981",
    pro: false,
    cat: "protect",
    title: "Снять защиту PDF",
    description: "Снимай пароль и ограничения с PDF при наличии доступа.",
    keywords: ["unlock pdf", "снять защиту pdf"],
  },
  {
    id: "watermark",
    route: "/watermark-pdf",
    emoji: "💧",
    label: "Водяной знак",
    hint: "Добавь метку",
    accept: ".pdf",
    multi: false,
    color: "#38bdf8",
    pro: false,
    cat: "protect",
    title: "Водяной знак PDF",
    description: "Добавляй текстовый или графический водяной знак.",
    keywords: ["watermark pdf", "водяной знак pdf"],
  },
  {
    id: "sign",
    route: "/sign-pdf",
    emoji: "✍️",
    label: "Подписать PDF",
    hint: "Электронная подпись",
    accept: ".pdf",
    multi: false,
    color: "#f0abfc",
    pro: true,
    cat: "protect",
    title: "Подписать PDF",
    description: "Добавляй подпись в PDF-документ.",
    keywords: ["sign pdf", "подписать pdf"],
  },
  {
    id: "flatten",
    route: "/flatten-pdf",
    emoji: "🧱",
    label: "Свести слои PDF",
    hint: "Зафиксируй форму",
    accept: ".pdf",
    multi: false,
    color: "#14b8a6",
    pro: true,
    cat: "protect",
    title: "Свести слои PDF",
    description: "Сделай PDF статичным, зафиксировав формы и аннотации.",
    keywords: ["flatten pdf", "свести pdf"],
  },
  {
    id: "repair",
    route: "/repair-pdf",
    emoji: "🛠️",
    label: "Восстановить PDF",
    hint: "Исправь поврежденный файл",
    accept: ".pdf",
    multi: false,
    color: "#f43f5e",
    pro: true,
    cat: "protect",
    title: "Восстановить PDF",
    description: "Попробуй восстановить структуру поврежденного PDF.",
    keywords: ["repair pdf", "восстановить pdf"],
  },
  {
    id: "redact",
    route: "/redact-pdf",
    emoji: "🕶️",
    label: "Скрыть данные",
    hint: "Редакция персональных данных",
    accept: ".pdf",
    multi: false,
    color: "#dc2626",
    pro: true,
    cat: "protect",
    title: "Скрыть данные в PDF",
    description: "Закрывай чувствительную информацию перед отправкой.",
    keywords: ["redact pdf", "скрыть данные pdf"],
  },

  {
    id: "info",
    route: "/analyze-pdf",
    emoji: "🔍",
    label: "Анализ PDF",
    hint: "Метаданные и свойства",
    accept: ".pdf",
    multi: false,
    color: "#84cc16",
    pro: false,
    cat: "analyze",
    title: "Анализ PDF",
    description: "Проверяй свойства, страницы и размер PDF-файла.",
    keywords: ["анализ pdf", "pdf info"],
  },
  {
    id: "extract",
    route: "/extract-text",
    emoji: "📝",
    label: "Извлечь текст",
    hint: "Текст из PDF",
    accept: ".pdf",
    multi: false,
    color: "#67e8f9",
    pro: false,
    cat: "analyze",
    title: "Извлечь текст из PDF",
    description: "Копируй текст из PDF в буфер или отдельный файл.",
    keywords: ["извлечь текст pdf", "pdf text"],
  },
  {
    id: "pdf2txt",
    route: "/pdf-to-text",
    emoji: "🧾",
    label: "PDF в TXT",
    hint: "Экспорт текста",
    accept: ".pdf",
    multi: false,
    color: "#7c3aed",
    pro: false,
    cat: "analyze",
    title: "PDF в TXT",
    description: "Сохраняй текст из PDF в формат TXT.",
    keywords: ["pdf в txt", "pdf to text"],
  },
  {
    id: "ocr",
    route: "/ocr-pdf",
    emoji: "👁️",
    label: "OCR текст",
    hint: "Распознавание сканов",
    accept: ".pdf,image/*",
    multi: false,
    color: "#e879f9",
    pro: true,
    cat: "analyze",
    title: "OCR PDF",
    description: "Распознавай текст в сканах и изображениях.",
    keywords: ["ocr pdf", "распознать текст"],
  },
  {
    id: "pagenum",
    route: "/page-numbers",
    emoji: "🔢",
    label: "Нумерация",
    hint: "Добавь номера страниц",
    accept: ".pdf",
    multi: false,
    color: "#86efac",
    pro: true,
    cat: "analyze",
    title: "Нумерация страниц PDF",
    description: "Добавляй номера страниц с выбором позиции.",
    keywords: ["нумерация pdf", "page numbers pdf"],
  },
  {
    id: "compare",
    route: "/compare-pdf",
    emoji: "🆚",
    label: "Сравнить PDF",
    hint: "Найди отличия",
    accept: ".pdf",
    multi: true,
    color: "#0ea5e9",
    pro: true,
    cat: "analyze",
    title: "Сравнить PDF",
    description: "Сравнивай версии PDF и находи изменения.",
    keywords: ["сравнить pdf", "compare pdf"],
  },
];

export const CATEGORIES = [
  { id: "all", label: "Все", emoji: "⚡" },
  { id: "convert", label: "Конвертация", emoji: "🔄" },
  { id: "edit", label: "Редактирование", emoji: "✏️" },
  { id: "protect", label: "Защита", emoji: "🛡️" },
  { id: "analyze", label: "Анализ", emoji: "📊" },
];

export const FREE_OPS_PER_DAY = 5;
export const PRO_PRICE = "$2.99/мес";